rawdata <- read.delim("household_power_consumption.txt", header = TRUE,  sep = ";", na.strings = "?")
certainDates <- rbind(subset(rawdata, rawdata$Date == "1/2/2007"), subset(rawdata,rawdata$Date == "2/2/2007") )
Date_Time <- strptime(paste(certainDates$Date, certainDates$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
myData<- cbind(Date_Time, certainDates[,3:9])
png(file = "plot3.png", width = 480, height = 480)
plot(myData$Date_Time, myData$Sub_metering_1, type = "l", xlab = " ", ylab = "Energy sub metering")
lines(myData$Date_Time, myData$Sub_metering_2, col = "red")
lines(myData$Date_Time, myData$Sub_metering_3, col = "blue")
legend("topright", pch = "___", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()

